name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
        stability: [prefer-stable]
        laravel: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
        include:
          - php: '7.1'
            laravel: '5.5.*'
            testbench: '3.5.*'
            stability: 'prefer-lowest'
          - laravel: '5.5.*'
            testbench: '3.5.*'
          - laravel: '5.6.*'
            testbench: '3.6.*'
          - laravel: '5.7.*'
            testbench: '3.7.*'
          - laravel: '5.8.*'
            testbench: '3.8.*'
          - laravel: '6.*'
            testbench: '4.*'
          - laravel: '7.*'
            testbench: '5.*'
          - laravel: '8.*'
            testbench: '6.*'
        exclude:
          # Unsupported version combinations
          - laravel: '6.*'
            php: '7.1'
          - laravel: '7.*'
            php: '7.1'
          - laravel: '8.*'
            php: '7.1'
          - laravel: '8.*'
            php: '7.2'
          - laravel: '5.5.*'
            php: '8.0'
          - laravel: '5.6.*'
            php: '8.0'
          - laravel: '5.7.*'
            php: '8.0'
          - laravel: '5.8.*'
            php: '8.0'
          # Cause deprecation warnings
          - laravel: '5.5.*'
            php: '8.1'
          - laravel: '5.6.*'
            php: '8.1'
          - laravel: '5.7.*'
            php: '8.1'
          - laravel: '5.8.*'
            php: '8.1'
          - laravel: '6.*'
            php: '8.1'
          - laravel: '7.*'
            php: '8.1'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
